version: '3.8'

services:
  api:
    image: fastapi-app:latest
    build:
      context: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - MODE=production # Production mode uses the image's copied files
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/dbname
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    restart: always

  api-dev:
    image: fastapi-app:latest
    build:
      context: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - MODE=development
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/dbname
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    restart: always
    volumes:
      # Mount the local source code directory
      # Override the production files with local files for development
      - .:/app

  db:
    image: postgres:17-bookworm
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:8.0-M02-bookworm
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  db-data:
  redis-data: